### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by miguelkennedy** [irinagain/iglu#107]
Hello,

Thanks for the great library! :)

Can anyone clarify if this is a bug?

The if statement here https://github.com/irinagain/iglu/blob/master/R/mage_ma_single.R#L211 has the same instructions as the else statement https://github.com/irinagain/iglu/blob/ccbfe50bfdbed749733e1edaf049adefa7bcaffd/R/mage_ma_single.R#L214

Thanks in advance

**Comment by irinagain** [comment]
Sorry for the delay on this; I was traveling. Let us look into this and get back to you

**Comment by irinagain** [comment]
This one should be corrected within a 1-2 weeks, I will keep you updated

**Comment by miguelkennedy** [comment]
Great! Thanks for keeping me posted!

**Comment by Nathaniel-Fernandes** [comment]
Hi! Thank you for your patience and identifying this bug.

PR #113 has been made that fixes this issue.

This is a copy-paste bug from copying lines [229-235](https://github.com/irinagain/iglu/blob/ccbfe50bfdbed749733e1edaf049adefa7bcaffd/R/mage_ma_single.R#L229) where the distinction between `nadir2peak = TRUE/FALSE`  matters (since you need the `max/min` glucose value, respectively, between the MA crosses to calculate `height2`). However, on line [211](https://github.com/irinagain/iglu/blob/ccbfe50bfdbed749733e1edaf049adefa7bcaffd/R/mage_ma_single.R#L211), we are at the end of the CGM trace so we use the last data point to calculate `height2` and tautologically `max(a) = min(a) = a`.

In other news, we plan to rewrite the `while` loop that eliminates turning points (lines [223-277](https://github.com/Nathaniel-Fernandes/iglu/blob/30ed212a4de5bc2a2884926db5e8319be30faf93/R/mage_ma_single.R#L223) in PR) in order to handle gaps in the data.

Thank you once again for the excellent find.
