### ISSUE TITLE
Another bug in MAGE algorithm

### ISSUE THREAD

**Issue by miguelkennedy** [irinagain/iglu#110]
Hello again.

I'm reporting a new bug in the MAGE algorithm.

In both these lines:
https://github.com/irinagain/iglu/blob/baaf291097eaeb1f261b145535ec76b656ce1369/R/mage_ma_single.R#L167
https://github.com/irinagain/iglu/blob/baaf291097eaeb1f261b145535ec76b656ce1369/R/mage_ma_single.R#L171

You're assuming that in both of them (.data$gl[s1:s2], na.rm = TRUE) will always return at least one value that's not NA but in some datasets this will return an empty vector because all values in that range s1:s2 are NA and the min and max of an empty vector is always infinite, resulting in a NA result for the overall MAGE calculation.

I'm attaching a dataset where this occurs, I have a few more in case you need them. Just run the MAGE algorithm in this dataset and you'll see that the final result is NA due to the issue I pointed above.

Thanks for looking into this, I would submit a PR myself but I don't know what the algorithm should do when it encounters an edge case like this.
[mage-error.csv](https://github.com/irinagain/iglu/files/10075557/mage-error.csv)

**Comment by miguelkennedy** [comment]
Just to add a little more info, this is the error message reported in the console:

Warning in min(.data$gl[s1:s2], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf

**Comment by irinagain** [comment]
Thank you for providing an example. We have been revisiting the current code with the team and found some other minor things, so we will make a bigger update on the mage function. It will take some time, though, due to the upcoming holidays and the end of the academic semester. I appreciate your patience.

**Comment by miguelkennedy** [comment]
Thanks for looking into it. I did notice your recent comments in the code MAGE code, like this one :) https://github.com/irinagain/iglu/blob/baaf291097eaeb1f261b145535ec76b656ce1369/R/mage_ma_single.R#L127

Take your time, no hurries 👍🏼

Thank you!

**Comment by Nathaniel-Fernandes** [comment]
Hi! Thank you for your patience.

**1. Assumption good, just doesn't hold.**
After some thorough investigation, I have tracked down the source of the error. I believe the assumption made is fine (i.e., that there will be "at least one value that's not NA" in .data$gl[s1:s2]), _**so long as**_ it actually holds.

**2. Why doesn't it hold?** 
https://github.com/irinagain/iglu/blob/2ae14d62faf7a77ed0477a146c5633b04d49502c/R/mage_ma_single.R#L133

This line is the culprit. It only checks if the MA DIFF != NA. However, since all MAs lag, a (rare) situation can arise where a crossing point can be recorded when MA Delta != NA but the underlying glucose value is NA (see lines 1503:1507 in the image below).

![Image 5-20-23 at 2 09 PM](https://github.com/irinagain/iglu/assets/66634653/d8d8bf08-4fac-412e-b5c8-47ea4bd273c4)

**3. Solution**
The solution, which will be released in an update to the function shortly, is to check that the underlying glucose value is not NA. Change Line 133 to:

```    
if(
   !is.na(.data$gl[i]) && !is.na(.data$gl[i-1]) &&
   !is.na(.data$DIFF[i]) && !is.na(.data$DIFF[i-1])
)
```
