### ISSUE TITLE
Definition of hypoglycemia episode

### ISSUE THREAD

**Issue by m-ajie** [irinagain/iglu#117]
Hi there,

The current definition of level 1  hypoglycemia as per the international consensus (https://pubmed.ncbi.nlm.nih.gov/29162583/) is any cgm reading of <70–54 mg/dL (3.9–3.0 mmol/L) for at least 15 min. If I use the _episode_calculation_ function to calculate frequency of level 1 hypoglycemia with _lvl1_hypo_ and _lvl2_hypo_ threshold set at the aforementioned threshold,  does the level 1 frequency calculated include _all_ of the cgm reading below 70 mg/dL or only the ones within 70-54 mg/dL range? Thank you

**Comment by irinagain** [comment]
Hi, apologies for the delay on this, I was on leave in the summer. I just merged a pull request that corrects some issues in episode calculations and follows the most recent consensus for level 1 versus level 2. Due to the specifics of wording and definition of episodes, level 2 is considered a subset of level 1.
