### ISSUE TITLE
error in gri function

### ISSUE THREAD

**Issue by m-ajie** [irinagain/iglu#153]
I tried to run the gri() function from iglu on my dataset (see below), but got the following error: 
"Error:
! Failed to evaluate glue component {label}
Caused by error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 0"

I suspect that it is because the data does not contain readings on neither hypoglycemic nor hyperglycemic range? But I might be wrong about it. Would it be possible for you to solve the issue? Thank you

[gri_error_dataframe.xlsx](https://github.com/irinagain/iglu/files/15415076/gri_error_dataframe.xlsx)

**Comment by irinagain** [comment]
thank you for reporting, we are looking into this. It seems that one possible issue could be due to repeated glucose measurements at the same time point, but we need a bit more time to diagnose

**Comment by irinagain** [comment]
we confirmed it was a repeated measurement issue and pushed the update to github that automatically accounts for this, note that in your example gri is 0 due to lack of any reading in either range (but this is not a mistake). CRAN update will be coming later. Please let us know if you have any other issues
